export const dummySeats = [
  {
    id: 0,
    sectionId: 1,
    columnId: 1,
    rowId: 1,
    rowLabel: "A",
    columnLabel: "1",
    available: true,
},
  {
    id: 1,
    sectionId: 1,
    columnId: 2,
    rowId: 1,
    rowLabel: "A",
    columnLabel: "2",
    available: true,
},
  {
    id: 2,
    sectionId: 1,
    columnId: 3,
    rowId: 1,
    rowLabel: "A",
    columnLabel: "3",
    available: true,
},
  {
    id: 3,
    sectionId: 2,
    columnId: 4,
    rowId: 1,
    rowLabel: "A",
    columnLabel: "4",
    available: false,
},
  {
    id: 4,
    sectionId: 2,
    columnId: 5,
    rowId: 1,
    rowLabel: "A",
    columnLabel: "5",
    available: true,
},
  {
    id: 5,
    sectionId: 2,
    columnId: 6,
    rowId: 1,
    rowLabel: "A",
    columnLabel: "6",
    available: true,
},
  {
    id: 6,
    sectionId: 2,
    columnId: 7,
    rowId: 1,
    rowLabel: "A",
    columnLabel: "7",
    available: true,
},
{
    id: 7,
    sectionId: 3,
    columnId: 1,
    rowId: 2,
    rowLabel: "B",
    columnLabel: "1",
    available: false,
},
{
    id: 8,
    sectionId: 3,
    columnId: 2,
    rowId: 2,
    rowLabel: "B",
    columnLabel: "2",
    available: true,
},
{
    id: 9,
    sectionId: 3,
    columnId: 3,
    rowId: 2,
    rowLabel: "B",
    columnLabel: "3",
    available: true,
},
{
    id: 10,
    sectionId: 3,
    columnId: 4,
    rowId: 2,
    rowLabel: "B",
    columnLabel: "4",
    available: true,
},
]
